version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
    # - REPOSITORY_URI=543028534356.dkr.ecr.us-east-1.amazonaws.com/my-webapp-repo
      - REPOSITORY_URI=058264351046.dkr.ecr.us-east-1.amazonaws.com/apache-service
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 058264351046.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json

artifacts:
  files:

    - imageDetail.json


env:
  exported-variables:
    - ImageURI


