AWSTemplateFormatVersion: "2010-09-09"
Description: Manual Blue/Green ECS (ALB, BlueTG, GreenTG, Blue & Green Services)

Parameters:
  VpcId:
    Type: String
  Subnet1:
    Type: String
  Subnet2:
    Type: String
 

  EcsClusterName:
    Type: String
    Default: manual-bluegreen-cluster
  
  ECSServiceSG:
   Type: AWS::EC2::SecurityGroup::Id
  
  ImageBlue:
    Type: String
    Description: Docker image for BLUE service (e.g. <account>.dkr.ecr.<region>.amazonaws.com/repo:tag)

  ContainerPort:
    Type: Number
    Default: 80

  DesiredCountBlue:
    Type: Number
    Default: 2
  DesiredCountGreen:
    Type: Number
    Default: 1
  AssignPublicIp:
    Type: String
    Default: ENABLED
    AllowedValues: [ENABLED, DISABLED]
  AppVersion:
    Type: String
  SwitchTarget:
    Type: String
    Default: blue
    AllowedValues: [blue, green]

Resources:

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: New-ALB
      Scheme: internet-facing
      Type: application
      SecurityGroups:
        - !Ref ECSServiceSG
      Subnets: 
        - !Ref Subnet1
        - !Ref Subnet2

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TG


  TG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      Name: !Ref AppVersion
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: !Ref ContainerPort
      TargetType: ip
      HealthCheckPath: "/"
      Matcher:
        HttpCode: "200-399"


  ### Blue TaskDef
  BlueTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: apache-service
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      ContainerDefinitions:
        - Name: blue-app
          Image: !Ref ImageBlue
          PortMappings:
            - ContainerPort: !Ref ContainerPort
    



  BlueService:
    Type: AWS::ECS::Service
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    DependsOn:
     - ALB
    Properties:
      Cluster: !Ref EcsClusterName
      ServiceName: !Ref AppVersion
      TaskDefinition: !Ref BlueTaskDef
      DeploymentController:
       Type: ECS
      DesiredCount: !Ref DesiredCountBlue
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: !Ref AssignPublicIp
          SecurityGroups:
           - !Ref ECSServiceSG
          Subnets: 
           - !Ref Subnet1
           - !Ref Subnet2
      LoadBalancers:
        - ContainerName: blue-app
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TG

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: /

  #########################################
  # ECS Execution Role
  #########################################
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Path: /


